version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - mongo_db
    ports:
      - "3000:3000"
    networks:
      - snappy-network
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/snappy-notes
      MONGO_URL: mongodb://mongo_db:27017/snappy-notes

  postgres_db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5555:5432"
    volumes:
      - ./db_data/pgdata:/var/lib/postgresql/data
    networks:
      - snappy-network
    environment:
      POSTGRES_DB: snappy-notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo_db:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/mongo_data:/data/db
    networks:
      - snappy-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
networks:
  snappy-network:
    driver: bridge
