services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
      - mongo_db
    ports:
      - "3000:3000"
    networks:
      - snappy-network
    environment:
      NODE_ENV: production
      PG_DB_URL: postgres://snappy:snappy_v1@postgres_db:5555/snappy-notes
      MONGO_DB_URL: mongodb://root:password@mongo_db:27017/

  postgres_db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - snappy-network
    environment:
      POSTGRES_DB: snappy-notes
      POSTGRES_USER: snappy
      POSTGRES_PASSWORD: snappy_v1

  mongo_db:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - snappy-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - snappy-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
    driver: local
  mongo_data:
    driver: local
  jenkins_home:
    driver: local

networks:
  snappy-network:
    driver: bridge
